FROM python:3.10-slim
RUN apt-get update && \
    apt-get install -y python3 python3-pip && \
    apt-get install -y libpq-dev build-essential && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY ./no_2_fast_api/requirements.txt /app/
RUN pip3 install --no-cache-dir -r requirements.txt

COPY ./no_2_fast_api/poke_api.py /app/

EXPOSE 8000

CMD ["uvicorn", "poke_api:app", "--host", "0.0.0.0", "--port", "8000"]
